### ISSUE TITLE
Connect /ticket page to API

### ISSUE THREAD

**Issue by AdrianAndersen** [abakus-ntnu/united-ticket-system#30]
- Get a ticket ID from either a query param or a dynamic path. Eg. /ticket/yourTicketID
- Fetch ticket upon load
- Check the photo_consent of the fetched user:
  - if the user has registered consent -> show ticket
  - else, display the photo_consent prompt
- Connect the photo_consent prompt to call the api to set the consent for the user
- Display the actual ticket for the user (the user ID) if the ticket is active and unused
- If the ticket is used or inactive, display only a warning

**Comment by iselinee** [comment]
Solved in: #37
