### ISSUE TITLE
Support multiple events (Friday and Saturday)

### ISSUE THREAD

**Issue by AdrianAndersen** [abakus-ntnu/united-ticket-system#31]
The event is split into two days, so we have to find a solution. If we have little time, we can ignore this , and clear the DB between the events

**Comment by juniwbjerde** [comment]
Good catch! This completely slipped my mind when we first decided what we had to implement support for. I think it would be enough to just add a date array on each user for when their ticket is valid (either [22.04], [23.04] or [22.02, 23.04]) and then check if todays date is in the array when validating the ticket. Alternatively one could have two entries with a single date and then two different tickets, but that seems more messy to me. But we can discuss that in our next meeting, and as you said; if we don't have the time to implement it we can just wipe the database between the events, so it's no crisis either way:)
